export const SET_MAX_LENGTH = 'SET_MAX_LENGTH'
export const SET_MIN_LENGTH = 'SET_MIN_LENGTH'
export const SET_REMOVE_PUNCTUATION = 'SET_REMOVE_PUNCTUATION'
export const SET_REMOVE_SPACES = 'SET_REMOVE_SPACES'
